deploy:  provider: elasticbeanstalk  
region: "us-east-1" ### AWS region of your choice
app: "sample-docker-react" ### Your EB App name
env: "SampleDockerReact-env" ### Your EB App environment name
bucket_name: "elasticbeanstalk-us-east-2-XXXXXXXXXXXX" ### S3 bucket name
bucket_path: "sample-app" ### S3 folder name under S3 bucket above
on:
  branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_access_key: "$AWS_SECRET_KEY"